# Generated by Django 4.1.6 on 2024-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0002_customuser_info_team_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='info',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eval',
            name='System_collection',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eval',
            unique_together={('System_id', 'Round', 'Query', 'Metric')},
        ),
    ]
